name: CI

on:
  push:
    branches:
      - master
      - 'auto-cadence-upgrade/**'
      - staging
      - trying
  pull_request:
    branches:
      - master
      - 'auto-cadence-upgrade/**'

# test comment
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      run: echo "test"
